# Generated by Django 4.0.2 on 2022-03-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_category_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
