# Generated by Django 4.0.2 on 2022-04-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_commnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commnet',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='home.commnet'),
        ),
    ]
