# Generated by Django 4.0.1 on 2022-05-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_coupon_end_alter_coupon_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
